site_name: PITCHFORK wiki
docs_dir: docs
site_description: public wiki for the PITCHFORK!!5! project
copyright: 2017 (c) team PITCHFORK & contributors, CC-By-Sa 3.5
theme: alabaster
#theme_dir: alabaster
site_dir: /var/www/wiki
markdown_extensions:
  - wikilinks
  - codehilite

pages:
  - Home: 'index.md'
  - About: 'about.md'
  - Threatmodel: 'Threatmodel.md'
  - FAQ: 'FAQ.md'
  - 'User Manual': 'User_Manual.md'
  - 'Developer Manual':
       - 'Repositories': 'Repositories.md'
       - 'Firmware': 'Firmware.md'
       - 'Software': 'Software.md'
       - Hardware:
            - 'Testing the hardware': 'Hardware_testing.md'
            - 'Hardware measurements': "HW_measurements.md"
