site_name: PITCHFORK wiki
docs_dir: docs
site_description: public wiki for the PITCHFORK!!5! project
copyright: 2017 (c) team PITCHFORK & contributors, CC-By-Sa 3.5
theme: alabaster
#theme_dir: alabaster
site_dir: /tmp/wiki
markdown_extensions:
  - wikilinks
  - codehilite

pages:
  - ['index.md', 'Home']
