site_name: PITCHFORK wiki
docs_dir: docs
#site_description: public wiki for the PITCHFORK!!5! project
copyright: 2017 (c) team PITCHFORK & contributors, CC-By-Sa 3.5
theme: alabaster
theme_dir: custom_theme
site_dir: /var/www/wiki
markdown_extensions:
  - wikilinks
  - codehilite
  - toc(permalink=true)
extra:
  logo: img/logo256x128inv.png
  logo_name: "wiki"
  include_toc: yes
  extra_nav_links:
     Git: /git/
     Twitter: https://twitter.com/pitchf___

pages:
  - Home: 'index.md'
  - About: 'about.md'
  - 'Threat model': 'Threatmodel.md'
  - FAQ: 'FAQ.md'
  - 'User Manual': 'User_Manual.md'
  - 'Developer Manual':
       - 'Repositories': 'Repositories.md'
       - 'Firmware': 'Firmware.md'
       - 'Software': 'Software.md'
       - Hardware:
           - 'USB form-factor': 'usb_token.md'
           - 'Nokia3310 form-factor': 'nokia.md'
           - 'Testing the hardware': 'Hardware_testing.md'
           - 'Hardware measurements': "HW_measurements.md"
  - "Crypto": "Crypto.md"
  - Known Bugs: "Bugs.md"
  - Thanks: "Thanks.md"
